In [1]:
import numpy as np
import pandas as pd
import plotly
import plotly.figure_factory as ff
import plotly.graph_objs as go
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True)

In [3]:
data = pd.read_csv('task_b.csv')
data=data.iloc[:,1:]

In [4]:
data.head()

f1            f2        f3    y
0  -195.871045 -14843.084171  5.532140  1.0
1 -1217.183964  -4068.124621  4.416082  1.0
2     9.138451   4413.412028  0.425317  0.0
3   363.824242  15474.760647  1.094119  0.0
4  -768.812047  -7963.932192  1.870536  0.0

In [5]:
data.corr()['y']

f1    0.067172
f2   -0.017944
f3    0.839060
y     1.000000
Name: y, dtype: float64

In [6]:
data.std()

f1      488.195035
f2    10403.417325
f3        2.926662
y         0.501255
dtype: float64

In [7]:
X=data[['f1','f2','f3']].values
Y=data['y'].values
print(X.shape)
print(Y.shape)

(200, 3)
(200,)


# What if our features are with different variance 

<pre>
* <b>As part of this task you will observe how linear models work in case of data having feautres with different variance</b>
* <b>from the output of the above cells you can observe that var(F2)>>var(F1)>>Var(F3)</b>

> <b>Task1</b>:
    1. Apply Logistic regression(SGDClassifier with logloss) on 'data' and check the feature importance
    2. Apply SVM(SGDClassifier with hinge) on 'data' and check the feature importance

> <b>Task2</b>:
    1. Apply Logistic regression(SGDClassifier with logloss) on 'data' after standardization 
       i.e standardization(data, column wise): (column-mean(column))/std(column) and check the feature importance
    2. Apply SVM(SGDClassifier with hinge) on 'data' after standardization 
       i.e standardization(data, column wise): (column-mean(column))/std(column) and check the feature importance

</pre>

<h3><font color='blue'> Make sure you write the observations for each task, why a particular feautre got more importance than others</font></h3>

In [ ]:
clf_l =SGDClassifier( loss='log', random_state=0, tol=1e-3)
clf_l.fit(X,Y)
clf_l.coef_

array([[-1481.82595196, 14346.68383705, 10505.38569407]])

In [ ]:
clf_h =SGDClassifier(loss='hinge', random_state=0, tol=1e-3)
clf_h.fit(X,Y)
clf_h.coef_

array([[10127.95322854, 14938.46440462, 10232.76549148]])

**********

In [8]:
clf=LogisticRegression(penalty='l2')
clf.fit(X,Y)

LogisticRegression()

In [20]:
std=clf.coef_[0]
print('Feature Importance Logistic Regression')
for id,i in enumerate(std):
  print('feature'+str(id+1)+'= '+str(abs(i)))
print ('Model accuracy score  = ',clf.score(X,Y))

Feature Importance Logistic Regression
feature1= 0.21574746239658452
feature2= 0.0751985942756508
feature3= 2.933699405940827
Model accuracy score  =  0.46


In [10]:
from sklearn.svm import LinearSVC
svm=LinearSVC(penalty='l2',loss='hinge',max_iter = 10000)
svm.fit(X,Y)

/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning:

Liblinear failed to converge, increase the number of iterations.



LinearSVC(loss='hinge', max_iter=10000)

In [19]:
std=svm.coef_[0]
print('Feature Importance SVM')
for id,i in enumerate(std):
  print('feature'+str(id+1)+'= '+str(abs(i)))
print ('Model accuracy score  = ',svm.score(X,Y))

Feature Importance SVM
feature1= 0.0006483414675483576
feature2= 0.00029675285381301254
feature3= 0.1061136724994679
Model accuracy score  =  0.57


*********

Observations:
1. In both the models feature3 is getting highest importance followed by feature1 and feature2
2. As standardization of data is not done the values are large and incoherent.
3. Feature3 has high variance hence it leads to overfitting as evident from negative feature importance

In [ ]:
scaler =StandardScaler()
x =scaler.fit_transform(X)
clf_l.fit(x,Y)
clf_l.coef_

array([[1.67992671, 0.45235761, 9.61806882]])

In [ ]:
clf_h.fit(x,Y)
clf_h.coef_

array([[0.08723916, 0.46595655, 9.98069984]])

*******

In [12]:
scaler=StandardScaler()
scaled_X=scaler.fit_transform(X)

In [13]:
clf=LogisticRegression(penalty='l2')
clf.fit(scaled_X,Y)

LogisticRegression()

In [17]:
std=clf.coef_[0]
print('Feature Importance Logistic Regression')
for id, i in enumerate(std):
  print('feature'+str(id+1)+"= "+str(abs(i)))
print('Model accuracy score  = ',clf.score(scaled_X,Y))

Feature Importance Logistic Regression
feature1= 0.21574746239658452
feature2= 0.0751985942756508
feature3= 2.933699405940827
Model accuracy score  =  0.925


In [15]:
clf=LinearSVC(penalty='l2',loss='hinge')
clf.fit(scaled_X,Y)

LinearSVC(loss='hinge')

In [18]:
std=clf.coef_[0]
print('Feature Importance SVM')
for id,i in enumerate(std):
  print('feature'+str(id+1)+'= '+str(abs(i)))
print('Model accuracy score  = ',svm.score(scaled_X,Y))

Feature Importance SVM
feature1= 0.21574746239658452
feature2= 0.0751985942756508
feature3= 2.933699405940827
Model accuracy score  =  0.825


******

Observations:
1. Here in both the models feature3 is getting highest importance and then feature1 and last is feature2.
2. Standadization of data makes the data more interpretable.
3. Feature3 has the high variance which leads to overfitting.
4. SVM model is performing better than logistic regression